// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: dashboard_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DashboardService_GetApplicationInformation_FullMethodName = "/aspire.v1.DashboardService/GetApplicationInformation"
	DashboardService_WatchResources_FullMethodName            = "/aspire.v1.DashboardService/WatchResources"
	DashboardService_WatchResourceConsoleLogs_FullMethodName  = "/aspire.v1.DashboardService/WatchResourceConsoleLogs"
	DashboardService_ExecuteResourceCommand_FullMethodName    = "/aspire.v1.DashboardService/ExecuteResourceCommand"
	DashboardService_WatchInteractions_FullMethodName         = "/aspire.v1.DashboardService/WatchInteractions"
)

// DashboardServiceClient is the client API for DashboardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DashboardServiceClient interface {
	GetApplicationInformation(ctx context.Context, in *ApplicationInformationRequest, opts ...grpc.CallOption) (*ApplicationInformationResponse, error)
	WatchResources(ctx context.Context, in *WatchResourcesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchResourcesUpdate], error)
	WatchResourceConsoleLogs(ctx context.Context, in *WatchResourceConsoleLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchResourceConsoleLogsUpdate], error)
	ExecuteResourceCommand(ctx context.Context, in *ResourceCommandRequest, opts ...grpc.CallOption) (*ResourceCommandResponse, error)
	WatchInteractions(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WatchInteractionsRequestUpdate, WatchInteractionsResponseUpdate], error)
}

type dashboardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDashboardServiceClient(cc grpc.ClientConnInterface) DashboardServiceClient {
	return &dashboardServiceClient{cc}
}

func (c *dashboardServiceClient) GetApplicationInformation(ctx context.Context, in *ApplicationInformationRequest, opts ...grpc.CallOption) (*ApplicationInformationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplicationInformationResponse)
	err := c.cc.Invoke(ctx, DashboardService_GetApplicationInformation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) WatchResources(ctx context.Context, in *WatchResourcesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchResourcesUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DashboardService_ServiceDesc.Streams[0], DashboardService_WatchResources_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchResourcesRequest, WatchResourcesUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DashboardService_WatchResourcesClient = grpc.ServerStreamingClient[WatchResourcesUpdate]

func (c *dashboardServiceClient) WatchResourceConsoleLogs(ctx context.Context, in *WatchResourceConsoleLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchResourceConsoleLogsUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DashboardService_ServiceDesc.Streams[1], DashboardService_WatchResourceConsoleLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchResourceConsoleLogsRequest, WatchResourceConsoleLogsUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DashboardService_WatchResourceConsoleLogsClient = grpc.ServerStreamingClient[WatchResourceConsoleLogsUpdate]

func (c *dashboardServiceClient) ExecuteResourceCommand(ctx context.Context, in *ResourceCommandRequest, opts ...grpc.CallOption) (*ResourceCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResourceCommandResponse)
	err := c.cc.Invoke(ctx, DashboardService_ExecuteResourceCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) WatchInteractions(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WatchInteractionsRequestUpdate, WatchInteractionsResponseUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DashboardService_ServiceDesc.Streams[2], DashboardService_WatchInteractions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchInteractionsRequestUpdate, WatchInteractionsResponseUpdate]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DashboardService_WatchInteractionsClient = grpc.BidiStreamingClient[WatchInteractionsRequestUpdate, WatchInteractionsResponseUpdate]

// DashboardServiceServer is the server API for DashboardService service.
// All implementations must embed UnimplementedDashboardServiceServer
// for forward compatibility.
type DashboardServiceServer interface {
	GetApplicationInformation(context.Context, *ApplicationInformationRequest) (*ApplicationInformationResponse, error)
	WatchResources(*WatchResourcesRequest, grpc.ServerStreamingServer[WatchResourcesUpdate]) error
	WatchResourceConsoleLogs(*WatchResourceConsoleLogsRequest, grpc.ServerStreamingServer[WatchResourceConsoleLogsUpdate]) error
	ExecuteResourceCommand(context.Context, *ResourceCommandRequest) (*ResourceCommandResponse, error)
	WatchInteractions(grpc.BidiStreamingServer[WatchInteractionsRequestUpdate, WatchInteractionsResponseUpdate]) error
	mustEmbedUnimplementedDashboardServiceServer()
}

// UnimplementedDashboardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDashboardServiceServer struct{}

func (UnimplementedDashboardServiceServer) GetApplicationInformation(context.Context, *ApplicationInformationRequest) (*ApplicationInformationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApplicationInformation not implemented")
}
func (UnimplementedDashboardServiceServer) WatchResources(*WatchResourcesRequest, grpc.ServerStreamingServer[WatchResourcesUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchResources not implemented")
}
func (UnimplementedDashboardServiceServer) WatchResourceConsoleLogs(*WatchResourceConsoleLogsRequest, grpc.ServerStreamingServer[WatchResourceConsoleLogsUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchResourceConsoleLogs not implemented")
}
func (UnimplementedDashboardServiceServer) ExecuteResourceCommand(context.Context, *ResourceCommandRequest) (*ResourceCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteResourceCommand not implemented")
}
func (UnimplementedDashboardServiceServer) WatchInteractions(grpc.BidiStreamingServer[WatchInteractionsRequestUpdate, WatchInteractionsResponseUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchInteractions not implemented")
}
func (UnimplementedDashboardServiceServer) mustEmbedUnimplementedDashboardServiceServer() {}
func (UnimplementedDashboardServiceServer) testEmbeddedByValue()                          {}

// UnsafeDashboardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DashboardServiceServer will
// result in compilation errors.
type UnsafeDashboardServiceServer interface {
	mustEmbedUnimplementedDashboardServiceServer()
}

func RegisterDashboardServiceServer(s grpc.ServiceRegistrar, srv DashboardServiceServer) {
	// If the following call panics, it indicates UnimplementedDashboardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DashboardService_ServiceDesc, srv)
}

func _DashboardService_GetApplicationInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationInformationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetApplicationInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetApplicationInformation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetApplicationInformation(ctx, req.(*ApplicationInformationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_WatchResources_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchResourcesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DashboardServiceServer).WatchResources(m, &grpc.GenericServerStream[WatchResourcesRequest, WatchResourcesUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DashboardService_WatchResourcesServer = grpc.ServerStreamingServer[WatchResourcesUpdate]

func _DashboardService_WatchResourceConsoleLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchResourceConsoleLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DashboardServiceServer).WatchResourceConsoleLogs(m, &grpc.GenericServerStream[WatchResourceConsoleLogsRequest, WatchResourceConsoleLogsUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DashboardService_WatchResourceConsoleLogsServer = grpc.ServerStreamingServer[WatchResourceConsoleLogsUpdate]

func _DashboardService_ExecuteResourceCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).ExecuteResourceCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_ExecuteResourceCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).ExecuteResourceCommand(ctx, req.(*ResourceCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_WatchInteractions_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DashboardServiceServer).WatchInteractions(&grpc.GenericServerStream[WatchInteractionsRequestUpdate, WatchInteractionsResponseUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DashboardService_WatchInteractionsServer = grpc.BidiStreamingServer[WatchInteractionsRequestUpdate, WatchInteractionsResponseUpdate]

// DashboardService_ServiceDesc is the grpc.ServiceDesc for DashboardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DashboardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aspire.v1.DashboardService",
	HandlerType: (*DashboardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetApplicationInformation",
			Handler:    _DashboardService_GetApplicationInformation_Handler,
		},
		{
			MethodName: "ExecuteResourceCommand",
			Handler:    _DashboardService_ExecuteResourceCommand_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchResources",
			Handler:       _DashboardService_WatchResources_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchResourceConsoleLogs",
			Handler:       _DashboardService_WatchResourceConsoleLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchInteractions",
			Handler:       _DashboardService_WatchInteractions_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "dashboard_service.proto",
}
